### ISSUE TITLE
Warp Pipe maximum range shorter than intended(?)

### ISSUE THREAD

**Issue by epicRedHot** [dayofpi/super_block_world#4]
When testing Warp Pipe functionality, it seems that the maximum range is 18 blocks instead of 80.
Maximum working range:
![image](https://user-images.githubusercontent.com/76829489/147526698-9d90203b-839f-4dd2-a90e-4cc002b3dd05.png)
![image](https://user-images.githubusercontent.com/76829489/147526732-7e77878a-b5a0-4dee-87ac-f9a16b6068b3.png)
Distance at which Warp Pipes no longer work:
![image](https://user-images.githubusercontent.com/76829489/147526815-84d91d3c-a0c5-44a2-9e6c-650bbab74ca1.png)
![image](https://user-images.githubusercontent.com/76829489/147526828-30fcbeaa-f5cc-4473-a37d-bc6bb3c9708f.png)

**Comment by dayofpi** [comment]
Thanks for letting me know, I found the source of the issue and I'll be fixing it soon

**Comment by dayofpi** [comment]
I believe its been fixed in the latest version, at least from my testing
