### ISSUE TITLE
Server Crash With Projectiles

### ISSUE THREAD

**Issue by Lhruggles** [dayofpi/super_block_world#5]
Projectiles will not be thrown by players, causing an error, but if a hammer bro or its variants throw something, the server straight up crashes:
[crash-2021-12-31_14.02.05-server.txt](https://github.com/dayofpi/super_block_world/files/7796400/crash-2021-12-31_14.02.05-server.txt)

**Comment by dayofpi** [comment]
Can you check if this is still happening for you in the latest version?

**Comment by Aaron995** [comment]
Still happening. 
https://pastebin.com/8KWh1sB8

**Comment by Foxxy-01** [comment]
ye still happening i think pls fix

**Comment by ghost** [comment]
Any ETA on when it will be fixed

**Comment by dayofpi** [comment]
I believe its been fixed

Edit: Yep, its good as of last version
