### ISSUE TITLE
Crash with requiem due to missing null check

### ISSUE THREAD

**Issue by Pyrofab** [dayofpi/super_block_world#7]
Original issue: Ladysnake/Requiem#470
https://github.com/dayofpi/super_block_world/blob/12370893b33d6808ab125d8c177372bf1a3f1424/src/main/java/com/dayofpi/super_block_world/main/common/entity/mob/goomba/GoombaEntity.java#L87-L90
`target` is marked as nullable but this method assumes it's not, causing a crash when some mod tries to unset a goomba's target. I believe the quickest fix would be to add another null check on line 88.

**Comment by dayofpi** [comment]
Ah thanks for letting me know! I'll fix it asap

**Comment by dayofpi** [comment]
A fix has been released to fix the missing null check
